### PR TITLE
First start on automated pylint 

### PR DESCRIPTION
**Pull request by fretchen**
There a few things to be noted:

- The `pre_measure` has inconstistent behavior as it sometimes returns a value and sometimes it do not. @RohitPrasadBhatt ?
- I could not find any example of how to use the`probabilites`, how it should be etc. Even on the website of pennylane.. Is there anything out there @cvjjm and @RohitPrasadBhatt ?

### CODE REVIEW

**Comment by RohitPrasadBhatt** [comment]
About probabilities :
https://pennylane.readthedocs.io/en/stable/code/api/pennylane.probs.html#pennylane.probs

**Comment by fretchen** [comment]
Perfect. I added a test. So from my side we are now fine and if it for you too, I would be happy to have this as new basis for the CI.

**Comment by cvjjm** [comment]
Looks good. @RohitPrasadBhatt feel free to merge.

**Comment by RohitPrasadBhatt** [comment]
Lets go!

**Pull request merged**
